CREATE TABLE Users(
	Id INT IDENTITY (1,1) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) UNIQUE NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL,
	Role NVARCHAR(50) CHECK(Role IN ('Admin', 'User')) NOT NULL
);

CREATE TABLE Products(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	PhotoURL NVARCHAR(255),
	Price DECIMAL(10,2) NOT NULL,
	DeliveryTime INT NOT NULL,
	Ingredients TEXT NOT NULL
);

CREATE TABLE Orders(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	UserId INT FOREIGN KEY REFERENCES Users(Id),
	ShippinhAddress NVARCHAR(255) NOT NULL,
	Notes TEXT,
	Status NVARCHAR(50) CHECK(Status IN ('Fulfilled', 'Unfulfilled')) NOT NULL,
	DateTime DATETIME NOT NULL DEFAULT GETDATE()
);


CREATE TABLE OrderDetails(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	OrderId INT FOREIGN KEY REFERENCES Orders(Id),
	ProductId INT FOREIGN KEY REFERENCES Products(Id),
	Quantity INT NOT NULL,
	PriceAtTheTimeOfOrder DECIMAL(10, 2) NOT NULL
);

